#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
char *sub[7]={"BTCS302- Data Communication","BTCS302- Data Communication","BTCS403- Data Structures & Algorithms","BTIBM401- Cloud Computing:Project Based Learning","BTIBM301- Application Development Using Java Programming","BTIT406- Unix & Shell Programming","BTIT407- Web Development"};
cout<<endl;
cout<<"KHYATI's SUBJECTS IN 3rd SEMESTER"<<endl;
cout<<endl;
for(int i=0;i<7;i++)
{
cout<<sub[i]<<endl;
}
getch();
}
